<a href="https://colab.research.google.com/github/ValeriiSlynko/IT-STEP-Practice/blob/master/Practice_Pandas/HmWrk_Pd(metrics_MAE_MSE_R2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Дані

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/HalyshAnton/ITStep-AI/refs/heads/superwised_learning/data/customer_spending.csv")

In [3]:
df.head()

,annual_income,account_tenure_days,age,engagement_score,support_tickets,annual_spending
0,57964.98,1170,65,35.95,5,218.46
1,27667.36,856,58,14.56,2,16.51
2,74068.69,1178,31,33.26,2,240.06
3,82232.89,741,33,87.93,2,242.77
4,16763.02,497,31,10.22,0,130.61

# Опис даних

Цу дані користувачів онлайн-сервісу **Shoply** — сайту, де люди купують товари та оформлюють підписки. Для кожного користувача зібрана інформація про його активність, дохід та взаємодію із сайтом.

* **annual_income** — скільки грошей користувач заробляє за рік
* **account_tenure_days** — скільки днів користувач зареєстрований на сайті
* **age** — вік користувача
* **engagement_score** — наскільки активно користувач користується сайтом
* **support_tickets** — скільки разів користувач звертався до служби підтримки
* **annual_spending** — скільки грошей користувач витрачає на сайті за рік


Потрібно спрогнозувати **витрати** на сайті за рік

# Завдання 1
Розділіть дані на ознаки для моделі(Х) та цільову змінну(y)

In [5]:
X = df.drop(columns=["annual_spending"])
y = df["annual_spending"]

In [6]:
X

,annual_income,account_tenure_days,age,engagement_score,support_tickets
0,57964.98,1170,65,35.95,5
1,27667.36,856,58,14.56,2
2,74068.69,1178,31,33.26,2
3,82232.89,741,33,87.93,2
4,16763.02,497,31,10.22,0
...,...,...,...,...,...
6515,22014.22,4428,41,94.80,3
6516,26082.07,71,42,44.61,1
6517,30162.82,178,18,17.03,3
6518,61570.17,312,22,54.99,1
6519,55293.82,3870,36,49.67,4

In [7]:
y

0       218.46
1        16.51
2       240.06
3       242.77
4       130.61
         ...
6515    141.48
6516    115.99
6517     75.06
6518     85.78
6519    180.58
Name: annual_spending, Length: 6520, dtype: float64

# Завдання 2
Розділіть дані на тренувальну та тестову вибірку

#Завдання 3
Нетренуйте дерево рішень на тренувальній вибірці

При створенні моделі використовуйте параметри за замовчуванням

# Завдання 4
Спронозуйте ціну автомобіля для тренувальних даних та порівняйте зі справжніми

Використайте метрики MAE, MSE, R2

# Завдання 5
Спронозуйте ціну автомобіля для тестових даних та порівняйте зі справжніми

Використайте метрики MAE, MSE, R2

# Завдання 6
Для різних значень параметра `max_depth` натренуйте модель та порахуйте метрику `MAE` на тренувальних та тестових даних

Отримайте відповідно 2 списки -- `train_mae` та `test_mae`
візуалізуйте їх

In [4]:
# код для візуалізації
# вам потрібно створити список max_depthes зі значеннями параметра який ви використовували
import matplotlib.pyplot as plt

plt.plot(max_depths, train_mae, label="Train MAE")
plt.plot(max_depths, test_mae, label="Test MAE")

plt.xlabel("max_depth")
plt.ylabel("MAE")
plt.title("Train and Test MAE depending on max_depth")
plt.legend()
plt.grid()

plt.show()

NameError: name 'max_depths' is not defined

# Завдання 7
По графіку визначте оптимальне значення параметра `max_depth`