<a href="https://colab.research.google.com/github/ValeriiSlynko/IT-STEP-Practice/blob/master/Practice_Pandas/HmWrk_Pd(metrics_MAE_MSE_R2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Дані

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/HalyshAnton/ITStep-AI/refs/heads/superwised_learning/data/customer_spending.csv")

* Показуємо поточний датасет із виводом перших 10 ряків

In [14]:
df.head(10)

,annual_income,account_tenure_days,age,engagement_score,support_tickets,annual_spending
0,57964.98,1170,65,35.95,5,218.46
1,27667.36,856,58,14.56,2,16.51
2,74068.69,1178,31,33.26,2,240.06
3,82232.89,741,33,87.93,2,242.77
4,16763.02,497,31,10.22,0,130.61
5,23951.86,1211,31,95.83,3,123.98
6,52591.63,1011,61,10.75,5,170.94
7,41194.77,587,38,36.20,0,144.48
8,48569.90,1438,40,60.63,3,137.69
9,30663.42,38,52,83.78,3,122.81

# Опис даних

Ці дані користувачів онлайн-сервісу **Shoply** — сайту, де люди купують товари та оформлюють підписки. Для кожного користувача зібрана інформація про його активність, дохід та взаємодію із сайтом.

* **annual_income** — скільки грошей користувач заробляє за рік
* **account_tenure_days** — скільки днів користувач зареєстрований на сайті
* **age** — вік користувача
* **engagement_score** — наскільки активно користувач користується сайтом
* **support_tickets** — скільки разів користувач звертався до служби підтримки
* **annual_spending** — скільки грошей користувач витрачає на сайті за рік


Потрібно спрогнозувати **витрати** на сайті за рік

* Визначаємо кількість рядків та стовпчиків

In [8]:
rows, columns = df.shape
print(f"Таблиця має '{rows}' рядків та '{columns}' стовпчиків/колнок")

Таблиця має '6520' рядків та '6' стовпчиків/колнок

* Отримуємо назви всіх стовпчиків та типи даних

In [9]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6520 entries, 0 to 6519
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   annual_income        6520 non-null   float64
 1   account_tenure_days  6520 non-null   int64
 2   age                  6520 non-null   int64
 3   engagement_score     6520 non-null   float64
 4   support_tickets      6520 non-null   int64
 5   annual_spending      6520 non-null   float64
dtypes: float64(3), int64(3)
memory usage: 305.8 KB


* Дивимось кількість пропусків у стовпчиків

In [10]:
df.isna().sum()

annual_income          0
account_tenure_days    0
age                    0
engagement_score       0
support_tickets        0
annual_spending        0
dtype: int64

# Завдання 1
Розділіть дані на ознаки для моделі(Х) та цільову змінну(y)

In [5]:
X = df.drop(columns=["annual_spending"])
y = df["annual_spending"]

In [15]:
# Після розділення даних перевіряємо 'Х'
X

,annual_income,account_tenure_days,age,engagement_score,support_tickets
0,57964.98,1170,65,35.95,5
1,27667.36,856,58,14.56,2
2,74068.69,1178,31,33.26,2
3,82232.89,741,33,87.93,2
4,16763.02,497,31,10.22,0
...,...,...,...,...,...
6515,22014.22,4428,41,94.80,3
6516,26082.07,71,42,44.61,1
6517,30162.82,178,18,17.03,3
6518,61570.17,312,22,54.99,1
6519,55293.82,3870,36,49.67,4

In [16]:
# Після розділення даних перевіряємо 'y'
y

0       218.46
1        16.51
2       240.06
3       242.77
4       130.61
         ...
6515    141.48
6516    115.99
6517     75.06
6518     85.78
6519    180.58
Name: annual_spending, Length: 6520, dtype: float64

# Завдання 2
Розділіть дані на тренувальну та тестову вибірку

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,     # 20% даних залишаємо для тестування
    random_state=42    # фіксуємо випадковість для відтворюваності результату
)

print("Тренувальна вибірка:", X_train.shape)
print("Тестова вибірка:", X_test.shape)

Тренувальна вибірка: (5216, 5)
Тестова вибірка: (1304, 5)

#Завдання 3
Нетренуйте дерево рішень на тренувальній вибірці

При створенні моделі використовуйте параметри за замовчуванням

# Завдання 4
Спронозуйте ціну автомобіля для тренувальних даних та порівняйте зі справжніми

Використайте метрики MAE, MSE, R2

# Завдання 5
Спронозуйте ціну автомобіля для тестових даних та порівняйте зі справжніми

Використайте метрики MAE, MSE, R2

# Завдання 6
Для різних значень параметра `max_depth` натренуйте модель та порахуйте метрику `MAE` на тренувальних та тестових даних

Отримайте відповідно 2 списки -- `train_mae` та `test_mae`
візуалізуйте їх

In [4]:
# код для візуалізації
# вам потрібно створити список max_depthes зі значеннями параметра який ви використовували
import matplotlib.pyplot as plt

plt.plot(max_depths, train_mae, label="Train MAE")
plt.plot(max_depths, test_mae, label="Test MAE")

plt.xlabel("max_depth")
plt.ylabel("MAE")
plt.title("Train and Test MAE depending on max_depth")
plt.legend()
plt.grid()

plt.show()

NameError: name 'max_depths' is not defined

# Завдання 7
По графіку визначте оптимальне значення параметра `max_depth`